### PR TITLE
fix rst syntax in the doc

### PR DESCRIPTION
**Pull request by fchapoton**
just a few more fixed details in doc formatting

found using

`sage --tox -e rst -- src/`

### CODE REVIEW

**Comment by fchapoton** [comment]
tox is locally satisfied on my computer, but fails to work at all in the github CI

**Comment by fredstro** [comment]
I’m working on it… I  will update the docker image to use sage 10.2 and see if that works. On 17 Feb 2024, at 20:07, Frédéric Chapoton ***@***.***> wrote:﻿
tox is locally satisfied on my computer, but fails to work at all in the github CI

**Comment by fchapoton** [comment]
maybe this is simple enough to be merged without the CI being green ?

**Review by fredstro — APPROVED** [review]
All OK

**Pull request merged**
